export const SET_SELECTED_VARIANT = 'SET_SELECTED_VARIANT';
export const TOGGLE_EXTRA = 'TOGGLE_EXTRA';
export const SET_QUANTITY = 'SET_QUANTITY';
export const RESET_PRODUCT_MENU = 'RESET_PRODUCT_MENU';
